name: github pages

on:
  push:
    branches:
      - master # default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: '16.14.2'
      - run: yarn
      - run: npm run docs:build
      - name: Deploy
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.CIM_TOKEN }}
          branch: gh-pages
          folder: docs-list
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.CIM_TOKEN }}
